# This file was generated by GoReleaser. DO NOT EDIT.
cask "gwt" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "7767383f2a9b1c4dd59b2429a4398e7f23a6a423a1cd44da3b7e5be580ce8424"
      url "https://github.com/sebjacobs/gwt/releases/download/v#{version}/gwt_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "62855dc99e6e0165cf8052b5d2391133a8100624cb8a3f6b2f0bc549ea3c25b3"
      url "https://github.com/sebjacobs/gwt/releases/download/v#{version}/gwt_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "20466444b9ebb43a6bbfed5567ee0fe62c8ea38bf91c0e7baf08575517e6873c"
      url "https://github.com/sebjacobs/gwt/releases/download/v#{version}/gwt_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "803b67c11d9f373274aa84f0f0e80b32c3e8bde0ac491811a1c94a79ee0fecdf"
      url "https://github.com/sebjacobs/gwt/releases/download/v#{version}/gwt_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gwt"
  desc "Fast git worktree manager pooling worktrees under .claude/worktrees/"
  homepage "https://github.com/sebjacobs/gwt"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gwt-bin"

  generate_completions_from_executable "gwt-bin", "completion",
    base_name: "gwt",
    shell_parameter_format: :cobra,
    shells: [:zsh]

  # No zap stanza required

  caveats <<~EOS
    gwt needs a shell function to change your shell's directory (a child
    process can't cd its parent). Load it from the binary by adding this to
    your ~/.zshrc:

      source <(gwt-bin shell)

    Then use `gwt` — e.g. `gwt add -b feature/login`, `gwt ls`, `gwt status`.
  EOS
end
