# This file was generated by GoReleaser. DO NOT EDIT.
cask "jotter" do
  version "0.8.0"

  on_macos do
    on_intel do
      sha256 "734555739e549917c681c812ca35f0885c4e1ddf227626aa21e109617f849133"
      url "https://github.com/sebjacobs/jotter/releases/download/v#{version}/jotter_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0efaeb8dc2dac0ffb161d09d1100e407cdabb3341930165da5a4ebf3876eba8f"
      url "https://github.com/sebjacobs/jotter/releases/download/v#{version}/jotter_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c17985d60a775874a2c9d2114b909399d4d49426545444c172d8eb81da85bcab"
      url "https://github.com/sebjacobs/jotter/releases/download/v#{version}/jotter_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "94862762c03cf06d31e8159f619ed9acfa4337903a1411966253817cf1c07d8d"
      url "https://github.com/sebjacobs/jotter/releases/download/v#{version}/jotter_#{version}_linux_arm64.tar.gz"
    end
  end

  name "jotter"
  desc "Append-only, git-backed log for Claude Code sessions"
  homepage "https://github.com/sebjacobs/jotter"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jotter"
  generate_completions_from_executable "jotter", "completion",
    base_name: "jotter",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

  caveats <<~EOS
    Run `jotter setup` once to wire jotter into Claude Code —
    it configures the data dir, installs the session skills, and
    grants the Bash(jotter:*) permission.
  EOS
end
