# This file was generated by GoReleaser. DO NOT EDIT.
cask "jotter" do
  version "0.14.0"

  on_macos do
    on_intel do
      sha256 "713d7d43f321767a2cb3d4c55949154145568461f8a416ba98b6d185a840dd9f"
      url "https://github.com/sebjacobs/jotter/releases/download/v#{version}/jotter_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "06db2bc025aed6614cf6a7fd7296d34e5f05f54845773b8af17861fd9db6956b"
      url "https://github.com/sebjacobs/jotter/releases/download/v#{version}/jotter_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "fbb7ab7b8a677c82eee2e0486d7f340cfeb0e2ea1e6037e53ecdaa11349dc425"
      url "https://github.com/sebjacobs/jotter/releases/download/v#{version}/jotter_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7348d812ed83ec327a5d0e5b02d0908382fcf9bf532eadf48f833bbb234752eb"
      url "https://github.com/sebjacobs/jotter/releases/download/v#{version}/jotter_#{version}_linux_arm64.tar.gz"
    end
  end

  name "jotter"
  desc "Append-only, git-backed log for Claude Code sessions"
  homepage "https://github.com/sebjacobs/jotter"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jotter"

  generate_completions_from_executable "jotter", "completion",
    base_name: "jotter",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

  caveats <<~EOS
    Run `jotter setup` once to wire jotter into Claude Code —
    it configures the data dir, installs the session skills, and
    grants the Bash(jotter:*) permission.
  EOS
end
