# This file was generated by GoReleaser. DO NOT EDIT.
cask "jotter" do
  version "0.13.0"

  on_macos do
    on_intel do
      sha256 "152c638e48fb56354e1b15e1f1c8052bc0306bdaa4de9ec6764b40e4a5a70a93"
      url "https://github.com/sebjacobs/jotter/releases/download/v#{version}/jotter_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "546d4aeb7d25866c4b5940ffef0b630846849c3dbeb9fc07f0b8423682d0e06e"
      url "https://github.com/sebjacobs/jotter/releases/download/v#{version}/jotter_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f5d3089d4a6351a73a70dbae2da80f7a5c2a2655e73b7d3a63386fb186b2a29e"
      url "https://github.com/sebjacobs/jotter/releases/download/v#{version}/jotter_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "44e93b555a3811797145a1ade7f57d74d390dd4c3e7d7ce3e29a7b0f308a2f15"
      url "https://github.com/sebjacobs/jotter/releases/download/v#{version}/jotter_#{version}_linux_arm64.tar.gz"
    end
  end

  name "jotter"
  desc "Append-only, git-backed log for Claude Code sessions"
  homepage "https://github.com/sebjacobs/jotter"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jotter"

  generate_completions_from_executable "jotter", "completion",
    base_name: "jotter",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

  caveats <<~EOS
    Run `jotter setup` once to wire jotter into Claude Code —
    it configures the data dir, installs the session skills, and
    grants the Bash(jotter:*) permission.
  EOS
end
